
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akash
 */
public class MovieList extends javax.swing.JFrame {

    /**
     * Creates new form MovieList
     */
    public MovieList() {
        
        initComponents();
        setTitle("MovieMatcher");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLableDateError = new javax.swing.JLabel();
        jButtonCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Movie Name", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        movieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movieTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome What Do You Wanna Watch  Today");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 190, 46));
        jLabel2.setText("Tell me the Date on which you wanna watch moive  :");

        jTextFieldDate.setText("DD-MM-YYYY");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
        });
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyTyped(evt);
            }
        });

        jButtonCheck.setText("submit");
        jButtonCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCheckMouseClicked(evt);
            }
        });
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });
        jButtonCheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonCheckKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLableDateError)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableDateError)
                    .addComponent(jButtonCheck))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int check()
       {
           //return 0 if Wrong Date return 1 if wrong Time
           String Date = jTextFieldDate.getText();
//           String Time = jTextFieldTime.getText();
            if(Date.length()==0)
                return 0;
           for(int i=0;i<Date.length();i++)
           {
               if(i==2||i==5)
               {
                   if(Date.charAt(i)!='-')
                    return 0;
               }
               else
               {
                   if(Date.charAt(i)>'9' || Date.charAt(i)<'0')
                       return 0;
               }
           }
//           for(int i=0;i<Time.length();i++)
//           {
//               if(i==2)
//               {
//                   if(Time.charAt(i)!=':')
//                        return 1;
//               }
//               else
//               {
//                   if(Time.charAt(i)>'9' || Time.charAt(i)<'0')
//                       return 1;
//               }
//           }
           return 2;
       }
    private void helpme()
    {
        jLableDateError.setText("");
        if(check()==0)
            {
                jLableDateError.setText("Please Check Date Format eg. 08-12-2016");
            }
            else
            {
                Connection conn = null;
                Statement stmt = null;
                ResultSet rs = null;
                String driver = "com.mysql.jdbc.Driver";
                String date = jTextFieldDate.getText(); 
                try {
                   Class.forName(driver);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }


               try {
                       conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/LoginDB","root","16402204");
                   } catch (SQLException ex) {
                       Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                   }
                String query = "select * from MovieTable where Date = \"" +date+"\";";
//                System.out.println(query);
                int flag = 1;
                
                try {
                    stmt = conn.createStatement();
                    rs = stmt.executeQuery(query);
                    DefaultTableModel model = (DefaultTableModel) movieTable.getModel();  //movieTable is The design Table;
                    int row = model.getRowCount();
                    for(int i=0;i<row;i++)
                    {
                        model.removeRow(0);
                        id--;
                    }
                    while(rs.next())
                    {
                        String movieName = rs.getString("Movie");
                        String dat = rs.getString("Date");
                        String time =rs.getString("Time");
                                
                        model.addRow(new Object[] {id,movieName,dat,time});
                        id++;
                        flag=0;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MovieList.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(flag==1)
                    jLableDateError.setText("No Movie Available.");
                

            }
    }
    private void jTextFieldDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
        {
            
            helpme();
        }
    }//GEN-LAST:event_jTextFieldDateKeyTyped

    private void jButtonCheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCheckKeyTyped
        // TODO add your handling code here:
         if(evt.getKeyChar()=='\n')
        {
            
            helpme();
        }
    }//GEN-LAST:event_jButtonCheckKeyTyped

    private void jButtonCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckMouseClicked
        // TODO add your handling code here:
        helpme();
    }//GEN-LAST:event_jButtonCheckMouseClicked

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
        jTextFieldDate.setText("");
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void movieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
         int row = movieTable.getSelectedRow();
         String movieName = (String) model.getValueAt(row, 1);
//         System.out.println(movieName);
         
        Booking book = new Booking(movieName+"Table",jTextFieldDate.getText());
        book.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_movieTableMouseClicked

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieList().setVisible(true);
            }
        });
    }
    private int id =1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLableDateError;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTable movieTable;
    // End of variables declaration//GEN-END:variables
}
